### ISSUE TITLE
Add config to change background and primary colors

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#4382]
## Why

After initial discussion of UI improvements, we decided to merge these two stories https://github.com/CoinAlpha/hummingbot/issues/4274 and https://github.com/CoinAlpha/hummingbot/issues/4270 to allow users configure the colors by storing the hex codes as configuration values to each parameter.

## What

Add a parameter to global config file in a section called COLOR SETTINGS that allows users to set the background color of each panel (top pane, bottom pane, output pane, input pane, logs pane) and the primary color of the terminal.

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/98640a91-13b6-42b0-a535-baeab2360f6c)

## Definition of Done

- [ ] Change the Hummingbot terminal color based on the param's default values
- [ ] Section `Color Settings` below the global configurations

Created the following parameters under Color Settings section:
- [ ] Param `top-pane` default: `#00000` (Black)
- [ ] Param `bottom-pane` default: `#00000` (Black)
- [ ] Param `output-pane` default: `#282C2F` (Blue Greyscale 500)
- [ ] Param `input-pane` default: `#151819` (Blue Greyscale 700)
- [ ] Param `logs-pane` default: `#151819` (Blue Greyscale 700)
- [ ] Param `terminal-primary` default: `#00FFE5` (Green)
